# Generated by Django 3.2.7 on 2021-09-02 11:38

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pathlib.PurePosixPath('/home/nanku/PycharmProjects/djangoProject_Wargaming/media'))),
            ],
        ),
    ]
