# Generated by Django 3.2.7 on 2021-09-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=128, null=True)),
                ('word_TF', models.FloatField(blank=True, null=True)),
                ('word_IDF', models.FloatField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=128, null=True)),
                ('word_TF', models.FloatField(blank=True, null=True)),
                ('word_IDF', models.FloatField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
