# Generated by Django 3.2.7 on 2021-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
