# Generated by Django 3.2.7 on 2021-09-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='word_IDF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='word_TF',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
